
name: Build KaivalKrupa Studio Live V3

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore SpotliveV3.csproj

      - name: Build EXE
        run: dotnet publish SpotliveV3.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o publish

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: KaivalKrupaStudioLive-Windows
          path: publish/
